version: 0.2

phases:

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - java -version
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/aws-build-sample-maven-project-0.0.1-SNAPSHOT.jar
